import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,realpath,mkdir,writeFile,symlink,readFile,chmod} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {loadConfig,scoped,textLimit,MAX_PROMPT} from '../dist/config.js';
import {Bridge} from '../dist/bridge.js';
import {hash} from '../dist/store.js';
async function setup(){const temp=await realpath(await mkdtemp(path.join(os.tmpdir(),'cos-bridge-')));const root=path.join(temp,'projects');await mkdir(root);const configFile=path.join(temp,'config.json');await writeFile(configFile,JSON.stringify({version:1,mode:'demo',roots:[root],projects:{Website:root},stateDir:path.join(temp,'state')}));const config=await loadConfig(configFile);const b=new Bridge(config);await b.init();return {b,config,root,temp};}
async function done(b,id){for(let i=0;i<80;i++){const r=await b.execute('bridge_receipt',{receiptId:id});if(['completed','failed','cancelled','uncertain'].includes(r.state))return r;await new Promise(r=>setTimeout(r,100));}throw Error('Job timeout');}
test('canonical allowlist rejects traversal, siblings and symlink escapes',async()=>{const {config,root,temp}=await setup();const outside=path.join(temp,'outside');await mkdir(outside);await symlink(outside,path.join(root,'escape'));for(const p of [outside,path.join(root,'../outside'),path.join(root,'escape')])await assert.rejects(scoped(config,p),{code:'OUTSIDE_ALLOWLIST'});assert.equal(await scoped(config,root),await scoped(config,path.join(root,'.')));});
test('default-deny config and broad home/root rejection',async()=>{const {temp}=await setup();for(const roots of [[],['/'],[os.homedir()]]){const f=path.join(temp,'bad.json');await writeFile(f,JSON.stringify({version:1,roots}));await assert.rejects(loadConfig(f));}});
test('UTF-8 byte bound and invalid Unicode fail before dispatch',()=>{assert.equal(textLimit('العربية',100,'test'),14);assert.throws(()=>textLimit('x'.repeat(MAX_PROMPT+1),MAX_PROMPT,'test'),{code:'SIZE_LIMIT'});assert.throws(()=>textLimit('\ud800',100,'test'),{code:'INVALID_TEXT'});});
test('project creation refuses overwrite and traversal name',async()=>{const {b,root}=await setup();const r=await b.execute('bridge_projects',{action:'create',parent:'Website',name:'Research'});assert.equal(r.path,path.join(root,'Research'));assert.equal(r.desktopRegistered,false);await assert.rejects(b.execute('bridge_projects',{action:'create',parent:root,name:'Research'}),{code:'ALREADY_EXISTS'});await assert.rejects(b.execute('bridge_projects',{action:'create',parent:root,name:'../escape'}));});
test('artifact preserves exact content, blocks overwrite and symlink escape',async()=>{const {b,root,temp}=await setup();const text='Research\nالعربية\t"quoted"';const a=await b.execute('bridge_artifact',{action:'write',project:root,name:'research.md',text});assert.equal(a.sha256,hash(text));assert.equal((await b.execute('bridge_artifact',{action:'read',project:root,name:'research.md'})).text,text);await assert.rejects(b.execute('bridge_artifact',{action:'write',project:root,name:'research.md',text}));const secret=path.join(temp,'outside.txt');await writeFile(secret,'private');await symlink(secret,path.join(root,'.cos-bridge-artifacts','escape.txt'));await assert.rejects(b.execute('bridge_artifact',{action:'read',project:root,name:'escape.txt'}),{code:'OUTSIDE_ALLOWLIST'});});
test('durable async submit, exact payload, idempotency, restart and external session continuation',async()=>{const {b,config,root}=await setup();const prompt='Deliver this whole prompt\nالعربية\nEnd.';const args={project:'Website',prompt,requestId:'test-request-001'};const first=await b.execute('bridge_submit',args);assert.equal(first.promptSha256,hash(prompt));const complete=await done(b,first.id);assert.equal(complete.state,'completed');const thread=await b.backend.demoRead(complete.threadId);assert.equal(thread.turns[0].items[0].content[0].text,prompt);const duplicate=await b.execute('bridge_submit',args);assert.equal(duplicate.id,first.id);await assert.rejects(b.execute('bridge_submit',{...args,prompt:'different'}),{code:'IDEMPOTENCY_CONFLICT'});const restarted=new Bridge(config);await restarted.init();assert.equal((await restarted.execute('bridge_receipt',{receiptId:first.id})).state,'completed');assert.equal((await restarted.execute('bridge_sessions',{project:root})).sessions.length,1);const follow=await restarted.execute('bridge_submit',{project:root,threadId:complete.threadId,prompt:'Follow up',requestId:'test-request-002'});assert.equal((await done(restarted,follow.id)).state,'completed');const external=await restarted.backend.demoStart(root);const imported=await restarted.execute('bridge_submit',{project:root,threadId:external.id,prompt:'Continue external session',requestId:'test-request-003'});assert.equal((await done(restarted,imported.id)).threadId,external.id);});
test('pre-Claude Codex request IDs keep their original fingerprint and replay',async()=>{const {b,root}=await setup();const prompt='legacy receipt';const requestId='codex-old-key-001';const input=[{type:'text',text:prompt}];const first=await b.execute('bridge_submit',{project:'Website',prompt,requestId});const oldFingerprint=hash(JSON.stringify({cwd:root,threadId:null,input,artifacts:[],onBusy:'reject',delivery:'direct',acceptDesktopPolicy:false,mode:'demo',sandbox:'read-only',model:null}));assert.equal(first.fingerprint,oldFingerprint);const saved=await b.store.get(first.id);delete saved.provider;await b.store.save(saved);assert.equal((await b.execute('bridge_submit',{project:'Website',prompt,requestId})).id,first.id);});
test('submission denies outside files, combined oversize and mismatched projects',async()=>{const {b,root,temp}=await setup();const p=path.join(temp,'private.txt');await writeFile(p,'secret');await assert.rejects(b.execute('bridge_submit',{project:root,promptFile:p,requestId:'deny-files-001'}),{code:'OUTSIDE_ALLOWLIST'});const a=await b.execute('bridge_artifact',{action:'write',project:root,name:'large.txt',text:'x'.repeat(MAX_PROMPT)});await assert.rejects(b.execute('bridge_submit',{project:root,prompt:'extra',artifacts:[a.path],requestId:'deny-large-001'}),{code:'SIZE_LIMIT'});const other=path.join(root,'Other');await mkdir(other);const t=await b.backend.demoStart(other);await assert.rejects(b.execute('bridge_submit',{project:root,threadId:t.id,prompt:'wrong project',requestId:'deny-match-001'}),{code:'PROJECT_MISMATCH'});});
test('state directory refuses symlink and public permissions',async()=>{const {temp,root}=await setup();const state=path.join(temp,'public-state');await mkdir(state,{mode:0o755});await chmod(state,0o755);const f=path.join(temp,'unsafe.json');await writeFile(f,JSON.stringify({version:1,roots:[root],stateDir:state}));await assert.rejects(loadConfig(f),{code:'CONFIG'});});
test('cancellation is confirmed and does not create a completed demo turn',async()=>{const {b,root}=await setup();const first=await b.execute('bridge_submit',{project:root,prompt:'Cancel me',requestId:'cancel-request-001'});await b.execute('bridge_cancel',{receiptId:first.id});const result=await done(b,first.id);assert.equal(result.state,'cancelled');if(result.threadId)assert.equal((await b.backend.demoRead(result.threadId)).turns.length,0);});
test('returned sandbox mismatch fails closed',async()=>{const {verifySandbox}=await import('../dist/backend.js');const {config,root}=await setup();assert.throws(()=>verifySandbox({cwd:root,approvalPolicy:'on-request',sandbox:{type:'readOnly',networkAccess:true}},config,root),{code:'POLICY_MISMATCH'});});
test('session management pins with confirmed metadata and preserves order of other tasks',async()=>{const {b,root}=await setup();b.config.mode='codex';const thread={id:'managed-thread',cwd:root,name:'Old',section:null};b.backend.read=async()=>thread;const calls=[];b.backend.withRpc=async fn=>fn({call:async(method,args)=>{calls.push({method,args});if(method==='thread/read')return {thread};if(method==='thread/name/set'){thread.name=args.name;return {};}if(method==='threadSection/list')return {data:[{id:'pinned-id',name:'Pinned'}],nextCursor:null};if(method==='thread/list')return {data:[{id:'existing-first'},{id:'existing-second'}]};if(method==='thread/section/move'){thread.section=args.sectionId?{id:args.sectionId,name:'Pinned'}:null;return {};}throw Error(method);}});const r=await b.execute('bridge_session_manage',{threadId:thread.id,title:'CoS bridge test',pin:true});assert.equal(r.pinned,true);assert.equal(r.name,'CoS bridge test');assert.equal(calls.find(c=>c.method==='thread/section/move').args.beforeThreadId,'existing-first');assert.equal(r.desktopVerified,false);await b.execute('bridge_session_manage',{threadId:thread.id,pin:false});assert.equal(thread.section,null);});
test('session management refuses outside scope before mutation',async()=>{const {b,temp}=await setup();b.backend.read=async()=>({id:'outside',cwd:temp});let mutated=false;b.backend.withRpc=async()=>{mutated=true;};await assert.rejects(b.execute('bridge_session_manage',{threadId:'outside',pin:true}),{code:'OUTSIDE_ALLOWLIST'});assert.equal(mutated,false);});

test('inherited object names are rejected as unknown tools',async()=>{const {b}=await setup();for(const name of ['constructor','toString','__proto__'])await assert.rejects(b.execute(name,{}),{code:'UNKNOWN_TOOL'});});
test('state child symlinks and receipt traversal fail closed',async()=>{const {b,config,root,temp}=await setup();for(const id of ['../../secret','/tmp/private','not-an-id'])await assert.rejects(b.execute('bridge_receipt',{receiptId:id}),{code:'INVALID_ID'});const {Store}=await import('../dist/store.js');const other=path.join(temp,'other-state');await mkdir(other,{mode:0o700});await symlink(root,path.join(other,'receipts'));await assert.rejects(new Store({...config,stateDir:other}).init(),{code:'CONFIG'});});
test('artifact symlinks cannot redirect reads into another allowed project',async()=>{const {b,root}=await setup();const first=path.join(root,'first');const second=path.join(root,'second');await mkdir(first);await mkdir(second);await b.execute('bridge_artifact',{action:'write',project:first,name:'seed.txt',text:'seed'});const secret=path.join(second,'notes.txt');await writeFile(secret,'other project');await symlink(secret,path.join(first,'.cos-bridge-artifacts','linked.txt'));await assert.rejects(b.execute('bridge_artifact',{action:'read',project:first,name:'linked.txt'}),{code:'OUTSIDE_ALLOWLIST'});});
