import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,realpath,writeFile} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {loadConfig,BridgeError} from '../dist/config.js';
import {Bridge} from '../dist/bridge.js';import {Store,hash} from '../dist/store.js';
import {runQueue,deliveredTurn,reconcileQueue} from '../dist/queue.js';
async function setup(){const temp=await realpath(await mkdtemp(path.join(os.tmpdir(),'queue-unit-')));const root=path.join(temp,'project');await mkdir(root);const f=path.join(temp,'config.json');await writeFile(f,JSON.stringify({version:1,mode:'codex',codexBinary:'/nonexistent-cos-test-codex',roots:[root],stateDir:path.join(temp,'state'),jobTimeoutSeconds:30}));const config=await loadConfig(f);const store=new Store(config);await store.init();const r={id:hash('queue-test'),key:'queue-test',fingerprint:'test',mode:'codex',cwd:root,threadId:'thread',state:'queued',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),promptBytes:5,promptSha256:hash('hello'),payloadSha256:hash('hello'),artifacts:[]};return {config,store,r};}
function fake(r,{busy=false,lost=false,scope=r.cwd}={}){let queue=[];let turns=[{id:'interrupted-before',status:'interrupted',items:[]}];const calls=[];return {calls,start:async()=>{},close(){},call:async(method,p)=>{calls.push({method,p});if(method==='thread/read')return {thread:{cwd:scope,turns}};if(method==='thread/queue/add'){queue=[{id:'queue-id',clientUserMessageId:p.clientUserMessageId,input:p.input}];if(lost)throw new BridgeError('TIMEOUT','Lost add response');return {queuedSubmission:queue[0]};}if(method==='thread/queue/list')return {data:queue,nextCursor:null};if(method==='thread/resume'){if(busy)throw new BridgeError('SESSION_BUSY','already has an active writer');return {}; }if(method==='thread/queue/start'){const turn={id:'recovered-turn',status:'completed',items:[{type:'userMessage',clientId:r.id,content:queue[0].input},{type:'agentMessage',text:'RECOVERED'}]};turns.push(turn);queue=[];return {turn};}throw Error(method);}};}
test('interrupted queue is started by exact ID and completed only after matching turn observation',async()=>{const {config,store,r}=await setup();const rpc=fake(r);const input=[{type:'text',text:'Exact العربية\n🙂'},{type:'text',text:'artifact'}];await runQueue(config,store,r,input,false,rpc);assert.equal(r.state,'completed');assert.deepEqual(rpc.calls.find(c=>c.method==='thread/queue/add').p.input,input);assert.equal(rpc.calls.find(c=>c.method==='thread/queue/start').p.queuedSubmissionId,'queue-id');assert.deepEqual(r.queueHistory.map(e=>e.state),['busy','preparing','queued','preparing','steered','delivered','completed']);assert.equal(rpc.calls.filter(c=>c.method==='thread/queue/add').length,1);});
test('Desktop writer keeps interrupted queue blocked, with no delivery claim or fork',async()=>{const {config,store,r}=await setup();const rpc=fake(r,{busy:true});await runQueue(config,store,r,[{type:'text',text:'hello'}],false,rpc);assert.equal(r.state,'blocked');assert.equal(r.queueObservation.needsSteer,true);assert.ok(!r.queueHistory.some(e=>['steered','delivered','completed'].includes(e.state)));assert.ok(!rpc.calls.some(c=>c.method==='thread/start'||c.method==='thread/queue/start'));});
test('lost enqueue response is uncertain and never retried',async()=>{const {config,store,r}=await setup();const rpc=fake(r,{lost:true});await runQueue(config,store,r,[{type:'text',text:'hello'}],false,rpc);assert.equal(r.state,'uncertain');assert.equal(rpc.calls.filter(c=>c.method==='thread/queue/add').length,1);assert.ok(!rpc.calls.some(c=>c.method==='thread/resume'));});
test('queue scope fails before dispatch; content similarity cannot establish delivery',async()=>{const {config,store,r}=await setup();const rpc=fake(r,{scope:path.dirname(r.cwd)});await runQueue(config,store,r,[],false,rpc);assert.equal(r.error.code,'OUTSIDE_ALLOWLIST');assert.ok(!rpc.calls.some(c=>c.method==='thread/queue/add'));assert.equal(deliveredTurn({turns:[{id:'other',items:[{type:'userMessage',clientId:'other',content:[{text:'hello'}]}]}]},r),undefined);});
test('queue missing without matching turn remains uncertain, not delivered',async()=>{const {config,store,r}=await setup();r.queuedSubmissionId='gone';r.queueMissingSince=Date.now()-31000;const rpc=fake(r);await reconcileQueue(rpc,config,store,r);assert.equal(r.state,'uncertain');});
test('desktop queue requires explicit policy consent before any dispatch',async()=>{const {config}=await setup();const b=new Bridge(config);await b.init();await assert.rejects(b.execute('bridge_submit',{project:config.roots[0],threadId:'thread',prompt:'hello',requestId:'consent-test',onBusy:'queue'}),{code:'DESKTOP_POLICY_REQUIRED'});});

test('adopted queue correlation preserves the original client message ID',()=>{const r={id:'bridge-receipt',queueClientMessageId:'original-cli-client'};const t={id:'turn',items:[{type:'userMessage',clientId:'original-cli-client'}]};assert.equal(deliveredTurn({turns:[t]},r),t);assert.equal(deliveredTurn({turns:[{items:[{type:'userMessage',clientId:'bridge-receipt'}]}]},r),undefined);});
test('queue inspection exposes inferred needs-steer without claiming Desktop UI state',async()=>{const {config,r}=await setup();const b=new Bridge(config);await b.init();b.backend.read=async()=>({id:r.threadId,cwd:r.cwd,turns:[{status:'interrupted',items:[]}]});b.queueItems=async()=>[{id:'existing',clientUserMessageId:'client'}];const view=await b.execute('bridge_sessions',{action:'read',threadId:r.threadId,includeQueue:true});assert.equal(view.queueStatus.needsSteer,true);assert.equal(view.queueStatus.desktopPauseState,'unknown');});
test('adopting a missing queue item cannot create a prompt or receipt',async()=>{const {config,r,store}=await setup();const b=new Bridge(config);await b.init();b.backend.read=async()=>({id:r.threadId,cwd:r.cwd});b.queueItems=async()=>[];await assert.rejects(b.execute('bridge_steer',{threadId:r.threadId,queuedSubmissionId:'gone',requestId:'adopt-missing-001',acceptDesktopPolicy:true}),{code:'QUEUE_NOT_FOUND'});assert.equal((await store.all()).length,0);});

test('ambiguous persisted owner dispatch never falls back to fresh direct queue start',async()=>{const {config,store,r}=await setup();r.ownerRecovery={state:'dispatching',at:new Date().toISOString(),fieldVerified:false};const rpc=fake(r);await runQueue(config,store,r,[{type:'text',text:'hello'}],false,rpc);assert.equal(r.state,'uncertain');assert.ok(!rpc.calls.some(c=>['thread/resume','thread/queue/start'].includes(c.method)));});
test('later automatic or human completion does not create owner recovery acknowledgement',async()=>{const {config,store,r}=await setup();r.deliveryRoute='desktop-queue';r.queuedSubmissionId='item';const rpc={call:async method=>method==='thread/read'?{thread:{cwd:r.cwd,turns:[{id:'later-turn',status:'completed',items:[{type:'userMessage',clientId:r.id}]}]}}:{data:[]}};await reconcileQueue(rpc,config,store,r);assert.equal(r.state,'completed');assert.equal(r.ownerRecovery,undefined);assert.ok(!r.queueHistory.some(e=>e.state==='steered'));});
